### ISSUE TITLE
Review Field Testing Documents - Leave Comments

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#1]
Review documents - leave comments

When done commenting - add a comment in docs (@alex@beaconhome.io - Reviewed) 

TOC
https://github.com/nosidewen/Field-Testing

**Comment by varitone** [comment]
I reviewed all. Some did not have a way for me to leave a comment. 
"Beaconhome" is used throughout.

**Comment by alexselig** [comment]
Perfecto! Thanks Steve
