### ISSUE TITLE
30-60-90 day goals 

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#15]
Draft up!

**Comment by varitone** [comment]
first draft posted

**Comment by alexselig** [comment]
Can you post a link here to it?

**Comment by varitone** [comment]
https://github.com/nosidewen/squad/blob/master/onboarding/goals/Steve%20McAllister%20306090

**Comment by varitone** [comment]
I am still concerned about how to go about finding people to beta test. 
However, I'll run it by a couple people I know. One friend is a very adept Facebook marketer. Would cutting that data (location, income, etc.) and spending a few bucks/day be appropriate?

**Comment by alexselig** [comment]
@steve Colin's trying to hire a FB marketer. Maybe he's a good candidate
for our team?

Budget is there for ads.

Alex


On Wed, Apr 25, 2018 at 12:28 PM, Steve McAllister <notifications@github.com

**Comment by varitone** [comment]
I have introduced Colin to my friend Jeff. 
We'll see how that goes.
