### ISSUE TITLE
Help Page on Website

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#16]
Can you create a getorro.com/help page for me? I would like the app to link here during next sprint. We can eventually redirect that URL to our FAQ (probably hosted by our Customer Support Management tool).

Content (regular text size is fine - please copy the formatting below):

**Comment by varitone** [comment]
Looks good & accurate. The mail link works.

On the bullet points, either all need punctuation or none do.

**Comment by alexselig** [comment]
➤ @beardedbadger commented:

@alex - Is this long term or immediately?

**Comment by alexselig** [comment]
➤ Alex Selig commented:

@beardedbadger this would be as soon as field testing starts. End of the month. Long term, I'm not sure if we'll keep the feedback feature on the switch or not.

**Comment by alexselig** [comment]
➤ @beardedbadger commented:

I'd rather not show a literal gif or video.  Can we crop out the witch and only show the UI?

**Comment by alexselig** [comment]
➤ Alex Selig commented:

For website I think we're ok not showing the image for now. The text is fine. The image will live in emails to customers.
