### ISSUE TITLE
Access to Zapier Account 

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#22]
@beardedbadger can you give me and @varitone access to Zapier? We want to start automating some flows.

**Comment by beardedbadger** [comment]
@alexselig we currently are using individual accounts.  Free for first 25 zaps.   I would recommend doing individuals unless you're going to push past the free limit at which we should probably evaluate the cost of a team account.

**Comment by alexselig** [comment]
➤ Alex Selig commented:

[@beardedbadger](https://app.asana.com/0/136329252939181/list) thanks for the info. Taken care of now
