### ISSUE TITLE
Create way for Alex  and steve to see if beta testers have paid

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#23]
@beardedbadger we need a way to see if people have paid. Can you help us here?

**Comment by beardedbadger** [comment]
@alexselig @varitone I've created a zap to forward Paypal emails when people pay.  It's being sent to both of you.  I am going to leave this issue open until we get our next payment and can confirm that the zap works.

**Comment by alexselig** [comment]
The ZAP didn't work @beardedbadger did you give me paypal access?

**Comment by alexselig** [comment]
➤ Alex Selig commented:

Update Paypal to go to AR@beaconhome.io

**Comment by alexselig** [comment]
➤ Steve McAllister commented:

Am I cc'd on this?

**Comment by alexselig** [comment]
➤ @beardedbadger commented:

[alexselig](https://app.asana.com/0/614028610878000/list)[Steve McAllister](https://app.asana.com/0/665374639011718/list) I added Support @beaconhome.io as an email.  PayPal says it’s waiting to be confirmed - I believe it needs to do email verification.  Once that’s done I will see if I can set up notifications

**Comment by varitone** [comment]
Yes - I got that email. 
It’s asking for my password to support@beaconhome.io <mailto:support@beaconhome.io> - - but that’s not anything I set up.
