### ISSUE TITLE
Need Phone Number for Support to Add to Terms + Condition

### ISSUE THREAD

**Issue by beardedbadger** [nosidewen/support#38]
@sukhdeep73 or @varitone I need a phone number to add to our terms and condition for people to call in relation to issues with product or orders. Do we have that number yet?  If so, what is it? 

Thanks!

**Comment by alexselig** [comment]
➤ Steve McAllister commented:

isn't it 747-253-0608

**Comment by sukhdeep73** [comment]
@varitone @beardedbadger Yes it is. 747-253-0608.

**Comment by alexselig** [comment]
➤ Steve McAllister commented:

This number now rings through to my phone.
VM is set up.

**Comment by beardedbadger** [comment]
Issue moved to [nosidewen/legal #19](https://github.com/nosidewen/legal/issues/19) via [**ZenHub**](https://www.zenhub.com/)
