### ISSUE TITLE
SETUP - Articles List --> Create list of help articles to write for setup + due dates

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#5]
Create a list of all the setup help articles that need to be written.

**Comment by varitone** [comment]
When we talked I had access to the project on Zeplin. 
Now when I click the link I get an error:

![Screen Shot 2018-04-11 at 5.24.49 PM.png](https://images.zenhubusercontent.com/5ac661654b5806bc2bcdd170/94dec762-e2e8-4e30-93df-d58af57c23d8)

**Comment by alexselig** [comment]
should now work! Janne added you.

**Comment by varitone** [comment]
06.4 Master Bedroom
06.5 Master Bedroom
07.1 Test Switch
07.1 Test Switch
07.2 Test Switch
07.2 Test Switch
07.3 Test Switch
07.3 Test Switch
08 Switch IQ
10 True Presence
11.2.1 Test Sleep
11.2.2 Test Sleep
11.3.1 Test Sleep
11.3.2 Test Sleep
11.4 Test Sleep
11.5.1 Test Sleep
11.5.2 Test Sleep
11.2B Test Preset
Wifi Setup Add Switch
Wifi Setup Connect Switch
Wifi Setup Connected Switch

21 total. Some of these are grey-ed out. Some may be redundant.

**Comment by alexselig** [comment]
Hi Steve - let's be a bit more descriptive here - let's make a list of
articles we need to write and then list underneath which steps in setup
will link to that article.

**Comment by varitone** [comment]
Well, yeah - this is just a list of every occurrence of HELP in the app.

Once I walk through the setup process myself I'll have more.

**Comment by varitone** [comment]
https://docs.google.com/spreadsheets/d/1qAxT5E7TrTPwvfWUxn-WORSM8_NsSyvNoXoz5MMiu7g/edit#gid=0

**Comment by alexselig** [comment]
Need to get access to view - can you hit the share button and use the drop
down to set to edit?

**Comment by varitone** [comment]
shared

**Comment by alexselig** [comment]
Def need to step up the content in here. Looking forward to seeing this
completed by Monday.

**Comment by varitone** [comment]
I could not get to the of the screens due to software issues. Will keep trying.

**Comment by varitone** [comment]
Yup. I found more instances, dropped them in the spreadsheet, and added some info and ideas.
